name: FPL Transfer Bot

on:
  workflow_dispatch:              # manual test button
  schedule:
    - cron: '30 14 * * 5'         # Fri 19:30 IST (14:30 UTC if DST differs)

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run
        env:
          FPL_TEAM_ID:      ${{ secrets.FPL_TEAM_ID }}
          TELEGRAM_TOKEN:   ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
