name: FPL Transfer Bot (self-hosted)

on:
  workflow_dispatch:
  schedule:
    - cron: '30 14 * * 5'

jobs:
  run-bot:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Use system Python (venv) & run
        env:
          FPL_EMAIL:        ${{ secrets.FPL_EMAIL }}
          FPL_PASSWORD:     ${{ secrets.FPL_PASSWORD }}
          FPL_TEAM_ID:      ${{ secrets.FPL_TEAM_ID }}
          TELEGRAM_TOKEN:   ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python3 -V
          python3 -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install chromium
          python main.py
